import { experiments, calculate } from './physics.js';
import { escapeHTML as esc, download, reportHTML, csvData, teacherHTML, worksheetHTML, trialTable } from './exports.js';
const $=id=>document.getElementById(id), STORAGE='fisica-viva-v1';
const blank=()=>({name:'',group:'',trials:[],work:Object.fromEntries(experiments.map(e=>[e.id,{prediction:'',conclusion:'',correct:false,complete:false,answer:null}]))});
let state=blank(),persistent=true;
try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved&&typeof saved==='object'){state.name=typeof saved.name==='string'?saved.name:'';state.group=typeof saved.group==='string'?saved.group:'';for(const exp of experiments){const w=saved.work?.[exp.id];if(w){state.work[exp.id]={prediction:typeof w.prediction==='string'?w.prediction:'',conclusion:typeof w.conclusion==='string'?w.conclusion:'',correct:w.correct===true,complete:w.complete===true,answer:Number.isInteger(w.answer)&&w.answer>=0&&w.answer<exp.options.length?w.answer:null};}}if(Array.isArray(saved.trials))state.trials=saved.trials.filter(t=>{const exp=experiments.find(e=>e.id===t?.id);return exp&&Number.isFinite(t.time)&&t.time>=0&&typeof t.date==='string'&&exp.params.every(p=>Number.isFinite(t.params?.[p.key])&&t.params[p.key]>=p.min&&t.params[p.key]<=p.max)&&exp.readings.every(([k])=>Number.isFinite(t.readings?.[k]));}).slice(-1000);}}catch{persistent=false;}
const params=Object.fromEntries(experiments.map(e=>[e.id,Object.fromEntries(e.params.map(p=>[p.key,p.value]))]));
const times=Object.fromEntries(experiments.map(e=>[e.id,0])),running=Object.fromEntries(experiments.map(e=>[e.id,false]));
let active=experiments[0], lab=null, tab='guide',speed=1,nearby=null,toastTimer,quality=innerWidth>650;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));persistent=true;}catch{persistent=false;}$('save-status').textContent=persistent?'Progreso guardado en este dispositivo':'Sin guardado local: descarga tu bitácora';}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4300);}
function setTab(value){tab=value;document.querySelectorAll('[data-tab]').forEach(b=>{const selected=b.dataset.tab===value;b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1;});for(const id of ['guide','lab','challenge'])$(id+'-pane').hidden=id!==value;document.querySelector('.panel-content').scrollTop=0;if(value==='lab'){updateReadings();drawChart();}}
function renderProgress(){const completed=experiments.filter(e=>state.work[e.id].complete).length;$('progress').value=completed;$('progress-label').textContent=`${completed} / 4`;$('trial-count').textContent=state.trials.length;$('experiment-list').innerHTML=experiments.map(e=>`<button class="experiment-link" data-experiment="${e.id}" aria-current="${e.id===active.id}" style="--item-color:${e.color}" aria-label="${esc(e.name)}${state.work[e.id].complete?', completado':''}"><span class="experiment-icon" aria-hidden="true">${e.icon}</span><span><strong>${esc(e.name)}</strong><small>${e.number} / ${esc(e.topic)}</small></span><span class="completion-dot">${state.work[e.id].complete?'✓':'↗'}</span></button>`).join('');}
function select(id,move=true){for(const key in running)running[key]=false;active=experiments.find(e=>e.id===id)||experiments[0];const w=state.work[active.id];document.documentElement.style.setProperty('--accent',active.color);$('experiment-topic').textContent=active.topic.toUpperCase();$('experiment-duration').textContent=active.duration;$('experiment-title').textContent=active.name;$('experiment-question').textContent=active.question;$('formula').textContent=active.formula;$('description').textContent=active.description;$('assumptions').textContent=active.assumptions;$('instructions').innerHTML=active.steps.map(s=>`<li>${esc(s)}</li>`).join('');$('prediction').value=w.prediction;$('conclusion').value=w.conclusion;
  $('parameters').innerHTML=active.params.map(p=>`<div class="parameter"><label for="param-${p.key}">${esc(p.label)}<output id="value-${p.key}" for="param-${p.key}">${params[active.id][p.key]} ${esc(p.unit)}</output></label><input type="range" id="param-${p.key}" data-param="${p.key}" min="${p.min}" max="${p.max}" step="${p.step}" value="${params[active.id][p.key]}" aria-valuetext="${params[active.id][p.key]} ${esc(p.unit)}"><div class="range-ends"><span>${p.min} ${esc(p.unit)}</span><span>${p.max} ${esc(p.unit)}</span></div></div>`).join('');
  $('readings').innerHTML=active.readings.map(([key,name,unit])=>`<div class="reading"><span>${esc(name)}</span><strong><output id="reading-${key}">0.00</output><small>${esc(unit)}</small></strong></div>`).join('');$('chart-label').textContent=active.graph;$('chart').setAttribute('aria-label',`Gráfica teórica: ${active.graph}`);$('quiz-question').textContent=active.quiz;$('quiz-options').innerHTML='<legend class="sr-only">Elige una respuesta</legend>'+active.options.map((o,i)=>`<label><input type="radio" name="quiz" value="${i}" ${w.answer===i?'checked':''}>${esc(o)}</label>`).join('');$('quiz-feedback').textContent=w.correct?active.feedback:'';$('extra-challenge').textContent=active.challenge;$('complete-button').textContent=w.complete?'✓ Experimento completado':'✓ Completar experimento';setTab('guide');renderProgress();updatePlay();updateReadings();updateRecordHint();if(move)lab?.focus(active.id);
}
function updatePlay(){$('play-button').textContent=running[active.id]?'Ⅱ Pausar':times[active.id]>0?'▶ Continuar':'▶ Iniciar';updateReadings();}
function updateRecordHint(){const n=state.trials.filter(t=>t.id===active.id).length;$('record-hint').textContent=`${n} ${n===1?'ensayo registrado':'ensayos registrados'}. Guarda al menos dos condiciones distintas.`;}
function updateReadings(){const r=calculate(active.id,params[active.id],times[active.id]);for(const[key]of active.readings)$("reading-"+key).textContent=r[key].toFixed(3);$('simulation-clock').textContent=times[active.id].toFixed(2)+' s';}
function drawChart(){const canvas=$('chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const p=params[active.id],r=calculate(active.id,p,times[active.id]);let xmax=8,ymin=-1,ymax=1,points=[],cursor;
  if(active.id==='projectile'){xmax=Math.max(1,r.range);ymin=0;ymax=Math.max(1,r.height*1.2);points=Array.from({length:101},(_,i)=>{const v=calculate(active.id,p,r.flight*i/100);return[v.x,v.y];});cursor=[r.x,r.y];}
  else if(active.id==='circuit'){xmax=12;ymin=0;ymax=12/p.resistance*1.2;points=[[0,0],[12,12/p.resistance]];cursor=[p.voltage,r.current];}
  else{ymax=active.id==='pendulum'?p.angle*1.25:p.amplitude*1.25;ymin=-ymax;xmax=Math.max(5,r.period*3);points=Array.from({length:181},(_,i)=>{const t=xmax*i/180,v=calculate(active.id,p,t);return[t,active.id==='pendulum'?v.theta*180/Math.PI:v.x];});const t=times[active.id]%xmax,v=calculate(active.id,p,t);cursor=[t,active.id==='pendulum'?v.theta*180/Math.PI:v.x];}
  const left=62,right=w-18,top=23,bottom=h-44;const px=x=>left+x/xmax*(right-left),py=y=>bottom-(y-ymin)/(ymax-ymin)*(bottom-top);
  ctx.font='17px monospace';ctx.textAlign='right';ctx.textBaseline='middle';for(let i=0;i<=4;i++){const y=ymin+(ymax-ymin)*i/4;ctx.strokeStyle='#30464e';ctx.beginPath();ctx.moveTo(left,py(y));ctx.lineTo(right,py(y));ctx.stroke();ctx.fillStyle='#a6bec0';ctx.fillText(y.toFixed(ymax<2?2:1),left-9,py(y));}ctx.textAlign='center';for(let i=0;i<=4;i++){const x=xmax*i/4;ctx.fillText(x.toFixed(1),px(x),bottom+23);}ctx.strokeStyle=active.color;ctx.lineWidth=3;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(px(x),py(y)):ctx.moveTo(px(x),py(y)));ctx.stroke();ctx.fillStyle='#fff4d5';ctx.beginPath();ctx.arc(px(cursor[0]),py(cursor[1]),6,0,Math.PI*2);ctx.fill();
}
function showNotebook(){$('student-name').value=state.name;$('student-group').value=state.group;$('notebook-content').innerHTML=state.trials.length?experiments.map(e=>{const trials=state.trials.filter(t=>t.id===e.id);return trials.length?`<h3>${esc(e.name)} ${state.work[e.id].complete?'✓':''}</h3><div class="table-scroll">${trialTable(e,trials)}</div>`:'';}).join(''):'<div class="empty-note">Tu primera pregunta es el punto de partida. Inicia un experimento y pulsa «Registrar ensayo» para guardar sus datos aquí.</div>';openDialog('notebook-dialog');}
function openDialog(id){lab?.stopInput();document.exitPointerLock?.();for(const k in running)running[k]=false;updatePlay();$(id).showModal();}
$('experiment-list').addEventListener('click',e=>{const button=e.target.closest('[data-experiment]');if(button)select(button.dataset.experiment);});
document.querySelectorAll('[data-tab]').forEach(b=>{b.addEventListener('click',()=>setTab(b.dataset.tab));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const tabs=['guide','lab','challenge'];setTab(tabs[(tabs.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3]);$('tab-'+tab).focus();});});
$('start-guide').addEventListener('click',()=>{if(state.work[active.id].prediction.trim().length<8){toast('Escribe primero una predicción breve y explica por qué.');$('prediction').focus();return;}setTab('lab');lab?.focus(active.id);});
for(const key of ['prediction','conclusion'])$(key).addEventListener('input',()=>{state.work[active.id][key]=$(key).value;if(state.work[active.id][key].trim().length<8)state.work[active.id].complete=false;save();renderProgress();});
$('parameters').addEventListener('input',e=>{const key=e.target.dataset.param;if(!key)return;const p=active.params.find(p=>p.key===key);params[active.id][key]=Number(e.target.value);$('value-'+key).textContent=`${e.target.value} ${p.unit}`;e.target.setAttribute('aria-valuetext',`${e.target.value} ${p.unit}`);times[active.id]=0;running[active.id]=false;updatePlay();updateReadings();drawChart();});
$('play-button').addEventListener('click',()=>{if(active.id==='projectile'&&times[active.id]>=calculate(active.id,params[active.id]).flight)times[active.id]=0;running[active.id]=!running[active.id];updatePlay();});
$('reset-button').addEventListener('click',()=>{times[active.id]=0;running[active.id]=false;updatePlay();updateReadings();drawChart();});
$('speed-select').addEventListener('change',e=>speed=Number(e.target.value));
$('record-button').addEventListener('click',()=>{if(times[active.id]<.1){toast('Inicia la simulación antes de registrar el ensayo.');return;}if(state.trials.length>=1000){toast('La bitácora llegó a 1,000 ensayos. Descarga tus resultados.');return;}state.trials.push({id:active.id,params:{...params[active.id]},readings:calculate(active.id,params[active.id],times[active.id]),time:times[active.id],date:new Date().toISOString()});save();renderProgress();updateRecordHint();toast('Ensayo guardado en tu bitácora. Cambia una variable y compara.');});
$('quiz-options').addEventListener('change',e=>{state.work[active.id].answer=Number(e.target.value);state.work[active.id].correct=false;state.work[active.id].complete=false;$('quiz-feedback').textContent='';$('complete-button').textContent='✓ Completar experimento';save();renderProgress();});
$('check-answer').addEventListener('click',()=>{const w=state.work[active.id];if(w.answer===null){$('quiz-feedback').textContent='Elige una respuesta para comprobar tu idea.';return;}w.correct=w.answer===active.answer;$('quiz-feedback').textContent=w.correct?'¡Bien razonado! '+active.feedback:'Revisa la relación entre las variables en la ecuación. Compara tus ensayos y vuelve a intentarlo.';save();});
$('complete-button').addEventListener('click',()=>{const w=state.work[active.id],distinct=new Set(state.trials.filter(t=>t.id===active.id).map(t=>JSON.stringify(active.params.map(p=>t.params[p.key]))));const missing=[];if(w.prediction.trim().length<8)missing.push('una predicción');if(distinct.size<2)missing.push('dos ensayos con parámetros distintos');if(!w.correct)missing.push('resolver el reto conceptual');if(w.conclusion.trim().length<8)missing.push('una conclusión con evidencia');if(missing.length){toast('Te falta: '+missing.join(', ')+'.');return;}w.complete=true;save();renderProgress();$('complete-button').textContent='✓ Experimento completado';toast('¡Investigación completada! Puedes explorar el siguiente aparato.');});
$('notebook-button').addEventListener('click',showNotebook);$('teacher-button').addEventListener('click',()=>openDialog('teacher-dialog'));$('help-button').addEventListener('click',()=>openDialog('help-dialog'));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
for(const [id,key]of [['student-name','name'],['student-group','group']])$(id).addEventListener('input',()=>{state[key]=$(id).value;save();});
$('download-csv').addEventListener('click',()=>{download('fisica-viva-datos.csv',csvData(state),'text/csv;charset=utf-8');toast('Datos CSV descargados.');});
$('download-report').addEventListener('click',()=>download('fisica-viva-informe.html',reportHTML(state)));
$('download-guide').addEventListener('click',()=>download('fisica-viva-guia-docente.html',teacherHTML()));
$('download-worksheet').addEventListener('click',()=>download('fisica-viva-hoja-investigacion.html',worksheetHTML()));
$('print-report').addEventListener('click',()=>{const old=$('print-frame');old?.remove();const frame=document.createElement('iframe');frame.id='print-frame';frame.title='Informe listo para imprimir';frame.style.cssText='position:fixed;width:1px;height:1px;left:-9999px;border:0';frame.srcdoc=reportHTML(state);frame.onload=()=>{frame.contentWindow.focus();frame.contentWindow.print();};document.body.append(frame);});
$('projection-button').addEventListener('click',()=>{const on=document.body.classList.toggle('projection');$('projection-button').textContent=on?'Salir del modo proyector':'Activar modo proyector';$('teacher-dialog').close();});
$('walk-button').addEventListener('click',()=>{lab?.startWalk();toast('W A S D para caminar · arrastra o mueve el ratón para mirar · Esc para salir.');});
$('overview-button').addEventListener('click',()=>lab?.overview());$('interact').addEventListener('click',()=>{if(nearby)select(nearby);});
$('quality-button').textContent=quality?'HD':'Eco';$('quality-button').addEventListener('click',()=>{quality=!quality;lab?.setQuality(quality);$('quality-button').textContent=quality?'HD':'Eco';toast(quality?'Calidad alta activada.':'Calidad reducida para un movimiento más fluido.');});
$('fullscreen-button').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('La pantalla completa no está disponible en este navegador.');}catch{toast('El navegador no permitió activar pantalla completa.');}});
document.addEventListener('pointerlockchange',()=>{$('crosshair').hidden=document.pointerLockElement!==$('scene');$('walk-button').textContent=document.pointerLockElement?'⌖ Recorriendo':'⌖ Recorrer salón';});
function sceneError(message){$('loading').hidden=true;$('scene-error').hidden=false;$('scene-error-text').textContent=message;}
$('teacher-dialog').append($('portable-download').content.cloneNode(true));
select('pendulum',false);save();
try{const { createLab }=await import('./scene.js');lab=createLab($('scene'),{onSelect:id=>select(id),onMove:({x,z,yaw})=>{$('map-player').setAttribute('transform',`translate(${100+x*7.4},${86+z*6.1}) rotate(${-yaw*180/Math.PI})`);},onNearby:id=>{nearby=id;$('interact').hidden=!id;if(id)$('interact').innerHTML=`Explorar ${esc(experiments.find(e=>e.id===id).name)} <kbd>E</kbd>`;},onError:sceneError});$('loading').hidden=true;
  let last=performance.now(),lastUI=0;function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!document.hidden){for(const exp of experiments){if(running[exp.id]){times[exp.id]+=dt*speed;if(exp.id==='projectile'){const end=calculate(exp.id,params[exp.id]).flight;if(times[exp.id]>=end){times[exp.id]=end;running[exp.id]=false;updatePlay();}}}}lab.updateModels(params,times,active.id,running);lab.render(dt,now);if(now-lastUI>80){if(tab==='lab'){updateReadings();drawChart();}lastUI=now;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
}catch(error){console.error('No se pudo iniciar el salón:',error);sceneError('El salón necesita WebGL 2 y sus archivos locales. Activa la aceleración gráfica o prueba un navegador actualizado. Las guías y la bitácora siguen disponibles.');}
