(function(){
'use strict';
const {labs,defaults}=PhysicsLab,$=id=>document.getElementById(id),KEY='guerrero-fisica-lab-v1';
let state={records:[],notes:{},passed:[],learner:''},storageOK=true;
try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&typeof s==='object'){
 state.records=Array.isArray(s.records)?s.records.filter(r=>r&&labs.some(l=>l.id===r.lab)&&r.params&&r.results&&typeof r.date==='string').slice(-300):[];
 state.notes=s.notes&&typeof s.notes==='object'&&!Array.isArray(s.notes)?s.notes:{};
 state.passed=Array.isArray(s.passed)?s.passed.filter(id=>labs.some(l=>l.id===id)):[];
 state.learner=typeof s.learner==='string'?s.learner.slice(0,100):'';
}}catch(e){storageOK=false;}
let index=0,params=defaults(labs[0]),tab='guide',room=null,running=false,elapsed=0,finished=false,last=0,toastTimer;
const fmt=n=>n===null?'—':Number(n).toLocaleString('es-PR',{maximumFractionDigits:2,minimumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>labs[index];
function notes(id=current().id){const n=state.notes[id];return n&&typeof n==='object'?n:{prediction:'',conclusion:''};}
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;notify('No se pudo guardar en este navegador. Descarga tu cuaderno para conservar el trabajo.');}updateProgress();}
function completed(l){const n=notes(l.id);const unique=new Set(state.records.filter(r=>r.lab===l.id).map(r=>JSON.stringify(r.params))).size;return unique>=2&&String(n.prediction||'').trim().length>=10&&String(n.conclusion||'').trim().length>=20&&state.passed.includes(l.id);}
function updateProgress(){const count=labs.filter(completed).length;$('progress-text').textContent=`${count} de 6 estaciones completadas`;$('progress-bar').style.width=`${count/6*100}%`;$('record-count').textContent=state.records.length;document.querySelectorAll('.station').forEach((b,i)=>b.classList.toggle('complete',completed(labs[i])));}
function selectStation(i){index=i;params=defaults(current());elapsed=0;finished=false;running=false;tab='guide';
 document.querySelectorAll('.station').forEach((b,j)=>{b.classList.toggle('active',j===i);b.setAttribute('aria-pressed',j===i);});
 const l=current();$('unit-label').textContent=`UNIDAD ${l.unit} / ESTACIÓN ${String(i+1).padStart(2,'0')}`;$('experiment-title').textContent=l.experiment;$('experiment-question').textContent=l.question;$('scene-title').textContent=l.title;$('scene-subtitle').textContent=l.subtitle;
 $('parameters').innerHTML=l.parameters.map(p=>p.options?`<div class="parameter"><label for="param-${p.key}">${p.label}</label><select id="param-${p.key}" data-param="${p.key}">${p.options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></div>`:`<div class="parameter"><label for="param-${p.key}">${p.label}<output id="output-${p.key}" for="param-${p.key}">${p.value} ${p.unit}</output></label><input id="param-${p.key}" data-param="${p.key}" type="range" min="${p.min}" max="${p.max}" step="${p.step}" value="${p.value}" aria-valuetext="${p.value} ${p.unit}"><div class="range-ends" aria-hidden="true"><span>${p.min} ${p.unit}</span><span>${p.max} ${p.unit}</span></div></div>`).join('');
 $('parameters').querySelectorAll('[data-param]').forEach(input=>input.addEventListener('input',()=>{
  const p=l.parameters.find(p=>p.key===input.dataset.param);params[p.key]=p.options?input.value:Number(input.value);
  if(!p.options){$('output-'+p.key).textContent=`${input.value} ${p.unit}`;input.setAttribute('aria-valuetext',`${input.value} ${p.unit}`);}
  reset();renderMetrics();drawChart();
 }));
 if(room)room.select(i,params);renderMetrics();drawChart();renderLearning();syncRun();
}
function syncRun(){$('sim-status').setAttribute('aria-live',running?'off':'polite');$('run-btn').textContent=running?'Ⅱ Pausar':finished?'▶ Repetir experimento':elapsed>0?'▶ Continuar':'▶ Iniciar experimento';$('record-btn').disabled=!finished;$('sim-status').textContent=finished?`Ensayo terminado · ${fmt(elapsed)} s`:elapsed>0?`En pausa · ${fmt(elapsed)} s`:'Listo para experimentar';}
function reset(){running=false;elapsed=0;finished=false;if(room)room.update(params,0);syncRun();}
function renderMetrics(){const l=current(),r=l.calculate(params);$('readouts').innerHTML=l.metrics(params,r).map(([name,v,unit])=>`<div class="readout"><span>${name}</span><strong>${fmt(v)}</strong><small>${unit}</small></div>`).join('');$('chart-description').textContent='Modelo ideal · Valores previstos para el ensayo. '+l.graphLabel+'.';$('chart').setAttribute('aria-label',l.graphLabel+'. '+l.metrics(params,r).map(([name,v,u])=>`${name}: ${fmt(v)} ${u}`).join('; '));}
function drawChart(){
 const l=current(),canvas=$('chart'),c=canvas.getContext('2d');if(!c)return;const w=canvas.width,h=canvas.height,pad={l:62,r:18,t:20,b:47},points=l.curve(params),second=l.secondCurve?l.secondCurve(params):[],all=points.concat(second);
 let xmin=Math.min(0,...all.map(p=>p[0])),xmax=Math.max(.1,...all.map(p=>p[0])),ymin=Math.min(0,...all.map(p=>p[1])),ymax=Math.max(.1,...all.map(p=>p[1]));
 if(ymin<0){ymin*=1.15;ymax*=1.15;}else ymax*=1.12;
 const x=v=>pad.l+(v-xmin)/(xmax-xmin)*(w-pad.l-pad.r),y=v=>h-pad.b-(v-ymin)/(ymax-ymin)*(h-pad.t-pad.b);
 c.clearRect(0,0,w,h);c.font='18px sans-serif';c.lineWidth=1;c.textAlign='right';
 for(let j=0;j<=3;j++){const v=ymin+(ymax-ymin)*j/3,yy=y(v);c.strokeStyle='#e4e7dc';c.beginPath();c.moveTo(pad.l,yy);c.lineTo(w-pad.r,yy);c.stroke();c.fillStyle='#73806d';c.fillText(Number(v.toFixed(2)),pad.l-10,yy+6);}
 c.textAlign='center';for(let j=0;j<=4;j++){const v=xmin+(xmax-xmin)*j/4;c.fillText(Number(v.toFixed(1)),x(v),h-pad.b+22);}
 const plot=(pts,color)=>{if(!pts.length)return;c.strokeStyle=color;c.lineWidth=4;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(x(p[0]),y(p[1])):c.moveTo(x(p[0]),y(p[1])));c.stroke();};
 plot(points,'#47785d');plot(second,'#d78550');c.font='16px sans-serif';c.fillStyle='#64715d';c.textAlign='right';c.fillText(l.axes[0],w-15,h-5);c.textAlign='left';c.fillText(l.axes[1],pad.l,15);
}
function renderLearning(){
 document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.tab===tab);b.tabIndex=b.dataset.tab===tab?0:-1;});$('learning-content').setAttribute('aria-labelledby','tab-'+tab);
 const l=current(),n=notes();
 if(tab==='guide'){$('learning-content').innerHTML=`<div class="guide-grid"><div><span class="step-number">A / ANTES DE EXPERIMENTAR</span><h3>Haz una predicción</h3><p>${l.predict}</p><label class="note-label" for="prediction">Tu hipótesis</label><textarea id="prediction" maxlength="3000" placeholder="Pienso que… porque…">${esc(n.prediction)}</textarea></div><div><span class="step-number">B / MANOS A LA CIENCIA</span><h3>Cambia una variable a la vez</h3><ol>${l.steps.map(t=>`<li>${t}</li>`).join('')}</ol></div><div><span class="step-number">C / DESPUÉS DE OBSERVAR</span><h3>Explica con evidencia</h3><p>Compara al menos dos ensayos y usa valores con sus unidades.</p><label class="note-label" for="conclusion">Tu conclusión</label><textarea id="conclusion" maxlength="4000" placeholder="Al cambiar… observé… Los datos muestran…">${esc(n.conclusion)}</textarea></div></div>`;
  for(const id of ['prediction','conclusion'])$(id).addEventListener('input',()=>{state.notes[l.id]={...notes(),[id]:$(id).value};save();});
 }else if(tab==='concept'){$('learning-content').innerHTML=`<div class="concept-grid"><div><span class="step-number">EL MODELO MATEMÁTICO</span><div class="formula">${l.formula}</div><p>Objetivo: ${l.objective}</p><p><strong>Conexión curricular:</strong> ${l.standard}</p></div><div><h3>¿Qué está ocurriendo?</h3><p>${l.explain}</p><h3>Condiciones del modelo</h3><p>${l.assumption}</p><h3>Para ir más lejos</h3><p>${l.extension}</p></div></div>`;
 }else{
  const count=new Set(state.records.filter(r=>r.lab===l.id).map(r=>JSON.stringify(r.params))).size;
  $('learning-content').innerHTML=`<div class="challenge"><span class="step-number">COMPRUEBA TU COMPRENSIÓN</span><h3>${l.quiz.question}</h3><div class="answers">${l.quiz.options.map((o,i)=>`<button data-answer="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="answer-feedback" role="status">${state.passed.includes(l.id)?'<p class="feedback">Ya resolviste correctamente esta comprobación. Puedes practicar de nuevo.</p>':''}</div><small>Para completar: hipótesis (10 caracteres), dos ensayos con ajustes distintos, conclusión con evidencia (20 caracteres) y respuesta correcta. Ensayos distintos: ${count}/2. ${completed(l)?'✓ Estación completada.':''}</small></div>`;
  document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const correct=Number(b.dataset.answer)===l.quiz.answer;if(correct&&!state.passed.includes(l.id))state.passed.push(l.id);save();$('answer-feedback').innerHTML=`<p class="feedback">${correct?'✓ Correcto. ':'Revisa el modelo y vuelve a intentarlo. '}${correct?l.quiz.feedback:'Consulta «Comprende la física» y compara tus mediciones.'}${completed(l)?' Estación completada.':''}</p>`;}));
 }
}
function record(){if(!finished)return;const l=current();state.records.push({lab:l.id,date:new Date().toISOString(),params:{...params},results:l.calculate(params),duration:elapsed});if(state.records.length>300)state.records.shift();save();notify('Medición guardada. Cambia una variable para comparar otro ensayo.');$('record-btn').disabled=true;}
function openModal(title,html){if(running){running=false;syncRun();}if(room)room.keys.clear();$('modal-title').textContent=title;$('modal-content').innerHTML=html;$('modal').showModal();}
function paramSummary(l,p){return l.parameters.map(v=>`${v.label}: ${v.options?(v.options.find(x=>x[0]===p[v.key])||[])[1]:fmt(p[v.key])+' '+v.unit}`).join(' · ');}
function notebook(){
 openModal('Tu cuaderno de laboratorio',`<p>Guarda tus mediciones y explica tus hallazgos. Este cuaderno pertenece únicamente a este navegador; descárgalo para entregarlo al profesor.</p><label for="learner">Nombre o equipo (opcional)</label><input id="learner" maxlength="100" value="${esc(state.learner)}" placeholder="Ej. Equipo Galileo"><div class="modal-actions"><button id="export-csv" class="dark-btn" ${state.records.length?'':'disabled'}>Descargar datos CSV</button><button id="export-notebook">Descargar cuaderno</button><button id="print-notebook">Imprimir / guardar PDF</button></div><div class="table-scroll"><table><thead><tr><th>Ensayo</th><th>Estación y ajustes</th><th>Resultados del modelo</th></tr></thead><tbody>${state.records.length?state.records.map((r,i)=>{const l=labs.find(l=>l.id===r.lab);return `<tr><td>${i+1}<small>${esc(new Date(r.date).toLocaleDateString('es-PR'))}</small></td><td><strong>${l.title}</strong><small>${esc(paramSummary(l,r.params))}</small></td><td>${l.metrics(r.params,r.results).map(([k,v,u])=>`${k}: ${fmt(v)} ${u}`).join('<br>')}</td></tr>`;}).join(''):'<tr><td colspan="3">Tu primera medición aparecerá aquí. Inicia un experimento, espera que termine y pulsa «Registrar medición».</td></tr>'}</tbody></table></div>${labs.filter(l=>notes(l.id).prediction||notes(l.id).conclusion).map(l=>`<h3>${l.unit} · ${l.title}</h3><p><strong>Hipótesis:</strong> ${esc(notes(l.id).prediction)}</p><p><strong>Conclusión:</strong> ${esc(notes(l.id).conclusion)}</p>`).join('')}`);
 $('learner').addEventListener('input',()=>{state.learner=$('learner').value;save();});$('export-csv').onclick=exportCSV;$('export-notebook').onclick=exportNotebook;$('print-notebook').onclick=()=>window.print();
}
function download(name,type,content){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCSV(){const cell=v=>'"'+String(v??'').replace(/^[=+\-@\t\r]/,"'$&").replace(/"/g,'""')+'"';const rows=[['Ensayo','Estudiante/equipo','Fecha','Unidad','Experimento','Variables','Magnitud','Valor SI','Unidad SI']];state.records.forEach((r,i)=>{const l=labs.find(l=>l.id===r.lab);l.metrics(r.params,r.results).forEach(([name,val,unit])=>rows.push([i+1,state.learner,r.date,l.unit,l.title,paramSummary(l,r.params),name,val,unit]));});download('fisica-mediciones.csv','text/csv;charset=utf-8','\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'));}
function exportNotebook(){let text=`CUADERNO DE FÍSICA · 12.º GRADO\nNombre o equipo: ${state.learner||'Sin indicar'}\nFecha: ${new Date().toLocaleDateString('es-PR')}\nModelos ideales; mediciones simuladas en SI.\n\n`;
 labs.forEach(l=>{const n=notes(l.id),records=state.records.filter(r=>r.lab===l.id);text+=`${l.unit} — ${l.title}\nObjetivo: ${l.objective}\nHipótesis: ${n.prediction||'Pendiente'}\n`;records.forEach((r,i)=>{text+=`Ensayo ${i+1}: ${paramSummary(l,r.params)}\n`+l.metrics(r.params,r.results).map(([k,v,u])=>`${k}: ${fmt(v)} ${u}`).join(' | ')+'\n';});text+=`Conclusión: ${n.conclusion||'Pendiente'}\nComprobación conceptual: ${state.passed.includes(l.id)?'Resuelta':'Pendiente'}\nEstación: ${completed(l)?'Completada':'En progreso'}\nCondiciones: ${l.assumption}\n\n`;});download('fisica-cuaderno.txt','text/plain;charset=utf-8',text);
}
function teacher(){const l=current();openModal('Un laboratorio para tu clase',`<p>Secuencia sugerida de 50 minutos para <strong>${l.title}</strong>. Organiza equipos de 2–3 estudiantes y alterna los roles de operador, observador y relator.</p><div class="modal-actions"><button id="projection" class="dark-btn">${document.body.classList.contains('projection')?'Salir de proyección':'Activar proyección'}</button><button id="worksheet">Hoja de trabajo imprimible</button><button id="reveal-answers">Ver respuestas docentes</button></div><div class="teacher-grid"><div class="teacher-card"><h3>01 · Activar ideas / 5 min</h3><p>${l.predict} Recoge las predicciones antes de ejecutar la simulación.</p></div><div class="teacher-card"><h3>02 · Demostrar / 10 min</h3><p>Selecciona «Mesa», identifica las variables y modela cómo cambiar una sola. Usa 0.5× para observar el movimiento.</p></div><div class="teacher-card"><h3>03 · Investigar / 25 min</h3><p>Los equipos realizan al menos dos ensayos, registran los valores con unidades y redactan una conclusión basada en evidencia.</p></div><div class="teacher-card"><h3>04 · Compartir / 10 min</h3><p>Discute resultados, resuelve «Ponte a prueba» y pide que entreguen el cuaderno descargado.</p></div></div><h3>Objetivo y conexión curricular</h3><p>${l.objective}<br><strong>${l.standard}</strong></p><h3>Evaluación formativa · 8 puntos</h3><p>Hipótesis razonada (2), control de variables y dos ensayos (2), datos con unidades (2), conclusión que relaciona datos y modelo (2). La marca de progreso indica actividades realizadas; la calidad de la explicación la evalúa el docente.</p><h3>Apoyos y profundización</h3><p><strong>Apoyo:</strong> modela el primer ensayo y ofrece la frase «Al cambiar ___ de ___ a ___, observé ___». <strong>Extensión:</strong> ${l.extension}</p><h3>Seguimiento en clase</h3><p>Cada dispositivo conserva su propio cuaderno. Recoge los archivos por el medio habitual de tu clase; no hay cuentas, envío automático ni panel compartido de calificaciones.</p><div id="teacher-answers" hidden><h3>Respuesta y explicación</h3><p>${l.quiz.options[l.quiz.answer]}. ${l.quiz.feedback}</p><p><strong>Idea clave:</strong> ${l.explain}</p></div>`);
 $('projection').onclick=()=>{document.body.classList.toggle('projection');$('modal').close();$('teacher-btn').textContent=document.body.classList.contains('projection')?'Salir de proyección ↙':'Espacio docente ↗';};$('worksheet').onclick=worksheet;$('reveal-answers').onclick=()=>{$('teacher-answers').hidden=!$('teacher-answers').hidden;$('reveal-answers').textContent=$('teacher-answers').hidden?'Ver respuestas docentes':'Ocultar respuestas';};
}
function worksheet(){const l=current();$('modal-title').textContent='Hoja de investigación · '+l.unit;$('modal-content').innerHTML=`<div class="modal-actions"><button id="print-sheet" class="dark-btn">Imprimir / guardar PDF</button></div><h3>${l.title}</h3><p>Nombre: ___________________________ Equipo: __________ Fecha: __________</p><p><strong>Objetivo:</strong> ${l.objective}</p><p><strong>Pregunta:</strong> ${l.predict}</p><h3>1. Mi hipótesis</h3><p>____________________________________________________________________</p><p>____________________________________________________________________</p><h3>2. Diseño experimental</h3><ol>${l.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p>Variable que cambio: __________________ Variable que mantengo: __________________</p><h3>3. Evidencia</h3><table><thead><tr><th>Ensayo</th><th>Ajustes y unidades</th><th>Resultados y unidades</th></tr></thead><tbody>${[1,2,3].map(i=>`<tr><td>${i}</td><td>________________________</td><td>________________________</td></tr>`).join('')}</tbody></table><h3>4. Mi conclusión</h3><p>¿Los datos apoyan mi hipótesis? Cito al menos dos mediciones.</p><p>____________________________________________________________________</p><p>____________________________________________________________________</p><h3>5. Transferencia</h3><p>${l.extension}</p><p><strong>Condiciones:</strong> ${l.assumption}</p><p>Conexión curricular: ${l.standard}</p>`;$('print-sheet').onclick=()=>window.print();}
function about(){openModal('Acerca de este laboratorio',`<p>Recurso de apoyo para Física de 12.º grado, elaborado a partir de los seis mapas curriculares de la carpeta «Curso de Física» facilitada por el profesor.</p><table><thead><tr><th>Mapa curricular consultado</th><th>Experimento de apoyo</th></tr></thead><tbody>${labs.map(l=>`<tr><td>${l.unit} · ${['Prácticas de ciencia e ingeniería','Cinemática del movimiento','Dinámica del movimiento','Trabajo y energía','Ondas','Transferencia y transformaciones de la energía'][labs.indexOf(l)]}</td><td>${l.title}<small>${l.standard}</small></td></tr>`).join('')}</tbody></table><p>Las estaciones cubren conceptos seleccionados de cada unidad; complementan el curso y los experimentos físicos. Las actividades y preguntas de esta página son una adaptación didáctica, no una reproducción ni una certificación oficial del currículo.</p><p>Consulta «Comprende la física» para ver las ecuaciones y condiciones de cada modelo. El salón representa los montajes a escala visual; las magnitudes físicas están en los controles, la gráfica y el cuaderno.</p><p>Motor gráfico: Three.js r128, licencia MIT. Los recursos del laboratorio se sirven desde la propia página.</p>`);}
$('stations').innerHTML=labs.map((l,i)=>`<button class="station" data-station="${i}" aria-pressed="${i===0}"><span class="station-number">${String(i+1).padStart(2,'0')}</span><span><strong>${l.short}</strong><small>UNIDAD ${l.unit}</small></span></button>`).join('');
$('stations').querySelectorAll('button').forEach(b=>b.onclick=()=>selectStation(Number(b.dataset.station)));
for(const b of document.querySelectorAll('[data-tab]')){b.onclick=()=>{tab=b.dataset.tab;renderLearning();};b.onkeydown=e=>{const buttons=[...document.querySelectorAll('[data-tab]')],i=buttons.indexOf(b);let next;if(e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();buttons[next].click();buttons[next].focus();}};}
$('run-btn').onclick=()=>{if(finished){elapsed=0;finished=false;}running=!running;syncRun();};$('reset-btn').onclick=reset;$('record-btn').onclick=record;
function setView(mode){if(!room){notify('La vista 3D no está disponible; usa los controles del experimento.');return;}room.view(mode);for(const name of ['overview','walk','focus']){$(name+'-btn').classList.toggle('active',name===mode);$(name+'-btn').setAttribute('aria-pressed',name===mode);}$('walk-pad').hidden=mode!=='walk';$('view-label').textContent={overview:'VISTA DEL SALÓN',walk:'RECORRIDO LIBRE',focus:'VISTA DEL EXPERIMENTO'}[mode];$('navigation-hint').textContent=mode==='walk'?'W A S D · Moverte / ← → · Girar / Arrastrar · Mirar':mode==='focus'?'Ajusta las variables y observa el experimento sobre la mesa.':'Selecciona una mesa o una estación para comenzar.';if(mode==='walk')$('scene').focus();}
for(const mode of ['overview','walk','focus'])$(mode+'-btn').onclick=()=>setView(mode);
$('fullscreen-btn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.querySelector('.room-panel').requestFullscreen)await document.querySelector('.room-panel').requestFullscreen();else notify('Usa «Activar proyección» en el espacio docente.');}catch(e){notify('No fue posible abrir pantalla completa. Usa el modo de proyección.');}};
$('notebook-btn').onclick=notebook;$('teacher-btn').onclick=()=>{if(document.body.classList.contains('projection')){document.body.classList.remove('projection');$('teacher-btn').textContent='Espacio docente ↗';}else teacher();};$('sources-btn').onclick=about;$('close-modal').onclick=()=>$('modal').close();
$('help-btn').onclick=()=>openModal('Cómo explorar el salón',`<p><strong>Salón:</strong> vista general de las seis estaciones. Selecciona una mesa o los botones de las unidades.</p><p><strong>Recorrer:</strong> pulsa sobre el salón y usa W A S D para caminar. Las flechas izquierda y derecha giran la mirada; también puedes arrastrar el ratón o el dedo. Las flechas en pantalla permiten recorrerlo desde una tableta.</p><p><strong>Mesa:</strong> acerca la cámara al experimento seleccionado. Los controles de la derecha cambian sus variables.</p><p><strong>Aprender:</strong> escribe una hipótesis, inicia el ensayo, registra al terminar y compara otra configuración. Explica los datos y completa la comprobación.</p><p>El teclado queda libre al seleccionar otro control. Puedes acceder a todas las actividades usando los botones de estación sin recorrer el salón.</p>`);
selectStation(0);updateProgress();
try{room=new PhysicsRoom($('scene'),i=>{selectStation(i);if(room.mode!=='walk')setView('focus');});}catch(e){$('scene-fallback').hidden=false;console.warn('Vista 3D no disponible:',e.message);for(const mode of ['overview','walk','focus'])$(mode+'-btn').disabled=true;}
if(!storageOK)notify('El guardado local no está disponible. Descarga tu cuaderno al terminar.');
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){running=false;syncRun();}});
function tick(ms){const dt=Math.min((ms-last)/1000,.05);last=ms;if(running){elapsed=Math.min(current().duration(params),elapsed+dt*Number($('speed').value));if(room)room.update(params,elapsed);if(elapsed>=current().duration(params)){running=false;finished=true;syncRun();}else $('sim-status').textContent=`En marcha · ${fmt(elapsed)} s`;}requestAnimationFrame(tick);}requestAnimationFrame(tick);
// Read-only diagnostics used during browser verification.
window.physicsDiagnostics=()=>({station:current().id,mode:room?.mode,camera:room?room.camera.position.toArray():null,elapsed,running,finished,records:state.records.length,completed:labs.filter(completed).length,webgl:!!room,drawCalls:room?.renderer.info.render.calls});
})();
